#!/bin/bash

clear

bash <(curl -s https://yar0slavvv.github.io/CPI-Nodes/logo_Cpi)

echo "__________Оберіть потрібне__________"
echo "     "
echo -e "(\033[38;5;244m1\033[0m) Встановити ноду (\033[38;5;244m2\033[0m) Оновити ноду"
echo "     "
echo "____________________________________"


read choice

case $choice in
 1)
    bash <(curl -s https://yar0slavvv.github.io/CPI-Nodes/installer)
    ;;
 2)
    bash <(curl -s https://yar0slavvv.github.io/CPI-Nodes/updater)
    ;;
  *)
    echo "Невірний вибір"
    ;;
esac
