#!/bin/bash

clear

if [ $n == "bash <(curl -s https://yar0slavvv.github.io/CPI-Nodes/logos/cpi)" ]; then
  bash <(curl -s https://yar0slavvv.github.io/CPI-Nodes/logos/cpi)

  echo "——————————Оберіть потрібне——————————"
  echo "     "
  echo -e "(\033[38;5;244m1\033[0m) Встановити ноду (\033[38;5;244m2\033[0m) Оновити ноду"
  echo "     "
  echo "____________________________________"
  echo "     "

  read choice

  case $choice in
   1)
      bash <(curl -s https://yar0slavvv.github.io/CPI-Nodes/installer)
      ;;
   2)
      bash <(curl -s https://yar0slavvv.github.io/CPI-Nodes/updater)
      ;;
    *)
      echo "Невірний вибір"
      ;;
esac

else
  bash <(curl -s https://yar0slavvv.github.io/CPI-Nodes/logos/acho)
fi
