#!/bin/bash

logo="bash <(curl -s https://yar0slavvv.github.io/CPI-Nodes/logos/cpi)"

if [ "$logo" == "bash <(curl -s https://yar0slavvv.github.io/CPI-Nodes/logos/cpi)" ]; then
  clear
  bash <(curl -s https://yar0slavvv.github.io/CPI-Nodes/logos/cpi)

  echo "——————————Оберіть потрібне——————————"
  echo "     "
  echo -e "(\033[38;5;244m1\033[0m) Встановити ноду (\033[38;5;244m2\033[0m) Оновити ноду"
  echo -e "(\033[38;5;244m3\033[0m) Видалити ноду   (\033[38;5;244m4\033[0m) Інструменти"
  echo "     "
  echo "____________________________________"
  echo "     "
while true; do
  read choice

  case $choice in
   1)
      bash <(curl -s https://yar0slavvv.github.io/CPI-Nodes/installer)
      ;;
   2)
      bash <(curl -s https://yar0slavvv.github.io/CPI-Nodes/updater)
      ;;
   3)
      bash <(curl -s https://yar0slavvv.github.io/CPI-Nodes/uninstall)
      ;;
   4)
      echo "в розробці")
      ;;
    *)
      echo "Невірний вибір"
      ;;
  esac
done

else
  bash <(curl -s https://yar0slavvv.github.io/CPI-Nodes/logos/acho)
fi
