#!/bin/bash

sudo apt-get update

sudo apt-get install whiptail

clear

sleep 1 && curl -s https://raw.githubusercontent.com/cpiteam/logo/main/logo | bash && sleep 1 

CHOICE=$(whiptail --title "CPI.TM" --menu "Оберіть ноду:" 15 60 5 \
"Subspace" "" \
"MUON" "" \
"Starknet" "" \
"Shardeum" "" \
"Nibiru" "" \
3>&1 1>&2 2>&3)

# Перевірте, який варіант був вибраний і виведіть повідомлення про вибір
case $CHOICE in
    "Subspace")
        whiptail --title "Subspace" --msgbox "норм хуйня" 10 60
        ;;
    "MUON")
        whiptail --title "MUON" --msgbox "єбать тєму обрали +2к" 10 60
        ;;
    "Starknet")
        whiptail --title "Starknet" --msgbox "стакрнет хуйня" 10 60
        ;;
    "Shardeum")
        bash <(curl -s https://yar0slavvv.github.io/CPI-Nodes/Shardeum)
    ;;
    "Nibiru")
        whiptail --title "Nibiru" --msgbox "блять це просто пізда, як же довго ти будеш її встановлювати" 10 60
        ;;
    *)
        whiptail --title "Error" --msgbox "Невірний вибір" 10 60
        ;;
esac
