#!/bin/bash

echo -e '\e[90m\e[32m'
echo -e '                                  '
echo -e '      _____           __          '
echo -e '     / ___/___ __    / /_________ '
echo -e '    / /  / _ // /   / __/ _  _  / '
echo -e '   / /__/  _// /_  / /_/ // // /  '
echo -e '  /____/_/  /_//_//___/_//_//_/   '
echo -e '                                  '
echo -e '\e[0m'
