#!/bin/bash

clear

sleep 1 && curl -s https://raw.githubusercontent.com/cpiteam/logo/main/logo | bash && sleep 1 

# Змінив список варіантів меню та виправив помилки у параметрах виклику команди whiptail
CHOICE=$(whiptail --title "Виберіть ноду" 15 60 5 \
"Subspace" "" \
"MUON" "" \
"Starknet" "" \
"Shardeum" "" \
"Nibiru" "" \
3>&1 1>&2 2>&3)

# Перевірте, який варіант був вибраний і виведіть повідомлення про вибір
case $CHOICE in
    "Subspace")
        whiptail --title "Subspace" --msgbox "Ви вибрали Subspace" 10 60
        ;;
    "MUON")
        whiptail --title "MUON" --msgbox "Ви вибрали MUON" 10 60
        ;;
    "Starknet")
        whiptail --title "Starknet" --msgbox "Ви вибрали Starknet" 10 60
        ;;
    "Shardeum")
        whiptail --title "Shardeum" --msgbox "Ви вибрали Shardeum, не було потрібно ображати користувачів" 10 60
        ;;
    "Nibiru")
        whiptail --title "Nibiru" --msgbox "Ви вибрали Nibiru" 10 60
        ;;
    *)
        whiptail --title "Error" --msgbox "Невірний вибір" 10 60
        ;;
esac
