#!/bin/bash

clear

sleep 1 && curl -s https://raw.githubusercontent.com/cpiteam/logo/main/logo | bash && sleep 1 

CHOICE=$(whiptail --title "Виберіть ноду" --menu - 15 60 5 \
-" "Subspace" \
-"MUON" \
-"Starknet" \
-"Shardeum" \
-"Nibiru" \
3>&1 1>&2 2>&3)

case $CHOICE in
    "Option 1")
        whiptail --title "Option 1" --msgbox "You chose option 1" 10 60
        ;;
    "Option 2")
        whiptail --title "Option 2" --msgbox "You chose option 2" 10 60
        ;;
    "Option 3")
        whiptail --title "Option 3" --msgbox "You chose option 3" 10 60
        ;;
    "Option 4")
        whiptail --title "Option 4" --msgbox "Ви вибрали Шардеум ідіть нахуй" 10 60
        ;;
    "Option 5")
        whiptail --title "Option 5" --msgbox "You chose option 5" 10 60
        ;;
    *)
        whiptail --title "Error" --msgbox "Invalid option" 10 60
        ;;
esac
