#!/bin/bash

clear

set -e

bash <(curl -s https://yar0slavvv.github.io/CPI-Nodes/shardeumlogo) 

sleep 2

clear

sudo apt update && sudo apt upgrade

sudo apt install containerd

clear

sudo apt install docker.io

clear

curl -O https://yar0slavvv.github.io/CPI-Nodes/installer.sh && chmod +x installer.sh && ./installer.sh
 

