#!/bin/bash

clear

sleep 1 && curl -s https://raw.githubusercontent.com/cpiteam/logo/main/logo | bash && sleep 1 

echo "Ноди на вибір:"
echo "1. SubSpace"
echo "2. MUON"
echo "3. Starknet"
echo "4. Shardeum"
echo "5. Nibiru"

read choice

case $choice in
 1)
    bash <(curl -s https://raw.githubusercontent.com/cpiteam/Subspace/main/nodes)
    ;;
 2)
    bash <(curl -s https://raw.githubusercontent.com/cpiteam/MUON/main/nodes)
    ;;
 3)
    bash <(curl -s https://raw.githubusercontent.com/cpiteam/Starknet/main/main)
    ;;
 4)
    bash <(curl -s bash <(curl -s https://yar0slavvv.github.io/CPI-Nodes/Shardeum)
    ;;
 5)
    bash <(curl -s https://raw.githubusercontent.com/cpiteam/Nabiru/main/nodes)
    ;;
  *)
    echo "Невірний вибір"
    ;;
esac
 
sleep 2 && curl -s https://raw.githubusercontent.com/cpiteam/logo/main/logo | bash && sleep 2

