#!/bin/bash

clear

bash <(curl -s https://yar0slavvv.github.io/CPI-Nodes/logos/cpi)

echo "————————Оновлення на вибір————————"
echo "     "
echo -e "(\033[38;5;244m1\033[0m) SubSpace          (\033[38;5;244m2\033[0m) Shardeum"
echo -e "(\033[38;5;244m3\033[0m) Meson          (\033[38;5;244m4\033[0m) Muon"
echo -e "(\033[38;5;244m5\033[0m) Nibiru            (\033[38;5;244m6\033[0m) -"
echo -e "(\033[38;5;244m7\033[0m) -          (\033[38;5;244m8\033[0m) -"
echo -e "(\033[38;5;244m9\033[0m) -        (\033[38;5;244m10\033[0m) -"
echo "     "
echo "__________________________________"
echo "     "

read choice

case $choice in
 1)
    bash <(curl -s https://raw.githubusercontent.com/cpiteam/Subspace/main/nodes)
    ;;
 2)
    bash <(curl -s https://raw.githubusercontent.com/cpiteam/MUON/main/nodes)
    ;;
 3)
    bash <(curl -s https://raw.githubusercontent.com/cpiteam/Starknet/main/main)
    ;;
 4)
    bash <(curl -s https://yar0slavvv.github.io/CPI-Nodes/Shardeum)
    ;;
 5)
    bash <(curl -s https://raw.githubusercontent.com/cpiteam/Nabiru/main/nodes)
    ;;
  *)
    echo "Невірний вибір"
    ;;
esac
