#!/bin/bash

logo="bash <(curl -s https://yar0slavvv.github.io/CPI-Nodes/logos/cpi)"

if [ "$logo" == "bash <(curl -s https://yar0slavvv.github.io/CPI-Nodes/logos/cpi)" ]; then
  clear
  bash <(curl -s https://yar0slavvv.github.io/CPI-Nodes/logos/cpi)

echo "————————Оновлення на вибір————————"
echo "     "
echo -e "(\033[38;5;244m1\033[0m) SubSpace          (\033[38;5;244m2\033[0m) Shardeum"
echo -e "(\033[38;5;244m3\033[0m) Meson             (\033[38;5;244m4\033[0m) Muon"
echo -e "(\033[38;5;244m5\033[0m) Nibiru            (\033[38;5;244m6\033[0m) Назад"
echo -e "(\033[38;5;244m7\033[0m) -                 (\033[38;5;244m8\033[0m) -"
echo -e "(\033[38;5;244m9\033[0m) -                 (\033[38;5;244m10\033[0m) -"
echo "     "
echo "__________________________________"
echo "     "

read choice

case $choice in
 1)
    bash <(curl -s https://yar0slavvv.github.io/CPI-Nodes/updates/subspace)
    ;;
 2)
    bash <(curl -s https://yar0slavvv.github.io/CPI-Nodes/updates/shardeum)
    ;;
 3)
    bash <(curl -s https://yar0slavvv.github.io/CPI-Nodes/updates/meson)
    ;;
 4)
    bash <(curl -s https://yar0slavvv.github.io/CPI-Nodes/updates/muon)
    ;;
 5)
    bash <(curl -s https://yar0slavvv.github.io/CPI-Nodes/updates/nibiru)
    ;;
 6)
    bash <(curl -s https://yar0slavvv.github.io/CPI-Nodes/choice)
    ;;
  *)
    echo "Невірний вибір"
    ;;
esac

else
  bash <(curl -s https://yar0slavvv.github.io/CPI-Nodes/logos/acho)
fi
