#!/bin/bash

clear

bash <(curl -s https://yar0slavvv.github.io/CPI-Nodes/logos/inst/lamina1)

echo "     "
avail_space=`df $PWD -h | awk '/[0-9]%/{print $(NF-2)}' | sed 's/.$//'`
echo -e "Наразі ви маєте $avail_space гб вільного місця, в той"
echo -e "час як Lamina1 потребує 200 гб та \e[31mUbuntu 22.04\e[39m"
echo "чи хочете випродовжити встановлення?"
echo "     "
echo -e "(\033[38;5;244m1\033[0m) Продовжити                 (\033[38;5;244m2\033[0m) Повернутися"
echo "     "
while true; do
  read a

  case $a in
   1)
      bash <(curl -s https://yar0slavvv.github.io/CPI-Nodes/nodes/launch/lamina1)
      ;;
   2)
      bash <(curl -s https://yar0slavvv.github.io/CPI-Nodes/installer)
      ;;
    *)
      echo "Невірний вибір"
      ;;
esac
done
