#!/bin/bash

clear

bash <(curl -s https://yar0slavvv.github.io/CPI-Nodes/logos/meson)

echo "     "
echo -e "(\033[38;5;244m1\033[0m) Продовжити             (\033[38;5;244m2\033[0m) Повернутися"
echo "     "
read -p choice

case $choice in
  1)
    echo "Ви обрали Варіант 1"
    # Виконання дій для Варіанту 1
    ;;
  2)
    echo "Ви обрали Варіант 2"
    # Виконання дій для Варіанту 2
    ;;
  *)
    echo "Невірний вибір. Будь ласка, введіть номер варіанту 1 або 2."
    ;;
esac
