#!/bin/bash

clear

bash <(curl -s https://yar0slavvv.github.io/CPI-Nodes/logos/inst/shardeum)

echo "     "
echo -e "(\033[38;5;244m1\033[0m) Продовжити                 (\033[38;5;244m2\033[0m) Повернутися"
echo "     "
while true; do
  read a
 
  case $a in
   1)
      bash <(curl -s https://yar0slavvv.github.io/CPI-Nodes/nodes/launch/shardeum)
      ;;
   2)
      bash <(curl -s https://yar0slavvv.github.io/CPI-Nodes/installer)
      ;;
    *)
      echo "Невірний вибір"
      ;;
esac
done
