#!/bin/bash

echo " "
echo "——————————————————————————————————————————————"
echo " "

#!/bin/bash
echo -e "\033[1;97;42mОновлення пакетів...\033[0m"
echo " "
sudo apt update
sudo apt install -y curl git jq lz4 build-essential unzip
echo " "
echo -e "\033[1;97;42mЗавантаження ноди...\033[0m"
echo " "
bash <(curl -s https://raw.githubusercontent.com/cpiteam/DeFund/main/dock include)
source .bash_profile

cd || return
rm -rf defund
git clone https://github.com/defund-labs/defund.git
cd defund || return
git checkout # 0.2.6
make install
defundd version # 0.2.6

defundd config keyring-backend os
defundd config chain-id orbit-alpha-1
defundd init "<Your moniker>" --chain-id orbit-alpha-1

echo " "
echo -e "\033[1;97;42mВстановлення genesis та addrbook...\033[0m"
echo " "
curl -Ls https://raw.githubusercontent.com/defund-labs/testnet/main/orbit-alpha-1/genesis.json > $HOME/.defund/config/genesis.json
curl -Ls https://raw.githubusercontent.com/cpiteam/DeFund/main/addrbook.json > $HOME/.defund/config/addrbook.json

APP_TOML="~/.defund/config/app.toml"
sed -i 's|^pruning *=.*|pruning = "custom"|g' $APP_TOML
sed -i 's|^pruning-keep-recent  *=.*|pruning-keep-recent = "100"|g' $APP_TOML
sed -i 's|^pruning-interval *=.*|pruning-interval = "10"|g' $APP_TOML

CONFIG_TOML="~/.defund/config/config.toml"
seeds="f902d7562b7687000334369c491654e176afd26d@170.187.157.19:26656,2b76e96658f5e5a5130bc96d63f016073579b72d@rpc-1.defund.nodes.guru:45656"
peers="d9184a3a61c56b803c7b317cd595e83bbae3925e@194.163.174.231:26677,5e7853ec4f74dba1d3ae721ff9f50926107efc38@65.108.6.45:60556,f114c02efc5aa7ee3ee6733d806a1fae2fbfb66b@65.108.46.123:56656,aa2c9df37e372c7928435075497fb0fb7ff9427e@38.129.16.18:26656,f2985029a48319330b99767d676412383e7061bf@194.163.155.84:36656,daff7b8cbcae4902c3c4542113ba521f968cc3f8@213.239.217.52:29656"
sed -i.bak -e "s/^persistent_peers *=.*/persistent_peers = \"$PEERS\"/" $CONFIG_TOML
sed -i.bak -e "s/^seeds =.*/seeds = \"$SEEDS\"/" $CONFIG_TOML
external_address=$(wget -qO- eth0.me)
sed -i.bak -e "s/^external_address *=.*/external_address = \"$external_address:26656\"/" $CONFIG_TOML
sed -i 's|^minimum-gas-prices *=.*|minimum-gas-prices = "0.025ufetf"|g' $CONFIG_TOML
sed -i 's|^prometheus *=.*|prometheus = true|' $CONFIG_TOML
sed -i 's/max_num_inbound_peers =.*/max_num_inbound_peers = 30/g' $CONFIG_TOML
sed -i 's/max_num_outbound_peers =.*/max_num_outbound_peers = 30/g' $CONFIG_TOML
sed -i -e "s/^filter_peers *=.*/filter_peers = \"true\"/" $CONFIG_TOML

sudo tee /etc/systemd/system/defundd.service > /dev/null << EOF
[Unit]
Description=Defund Node
After=network-online.target
[Service]
User=$USER
ExecStart=$(which defundd) start
Restart=on-failure
RestartSec=10
LimitNOFILE=10000
[Install]
WantedBy=multi-user.target
EOF
echo " "
echo -e "\033[1;97;42mSnapshot...\033[0m"
echo " "
URL="https://raw.githubusercontent.com/cpiteam/DeFund/main/Snapshot"
curl -L $URL | tar -Ilz4 -xf - -C $HOME/.defund

CONFIG_TOML="~/.defund/config/config.toml"
sed -i 's/timeout_propose =.*/timeout_propose = "100ms"/g' $CONFIG_TOML
sed -i 's/timeout_propose_delta =.*/timeout_propose_delta = "500ms"/g' $CONFIG_TOML
sed -i 's/timeout_prevote =.*/timeout_prevote = "100ms"/g' $CONFIG_TOML
sed -i 's/timeout_prevote_delta =.*/timeout_prevote_delta = "500ms"/g' $CONFIG_TOML
sed -i 's/timeout_precommit =.*/timeout_precommit = "100ms"/g' $CONFIG_TOML
sed -i 's/timeout_precommit_delta =.*/timeout_precommit_delta = "500ms"/g' $CONFIG_TOML
sed -i 's/timeout_commit =.*/timeout_commit = "1s"/g' $CONFIG_TOML
sed -i 's/skip_timeout_commit =.*/skip_timeout_commit = false/g' $CONFIG_TOML

sudo systemctl daemon-reload
sudo systemctl enable defundd
sudo systemctl start defundd

sudo journalctl -u defundd -f -o cat

snapshot_interval=0
sed -i.bak -e "s/^snapshot-interval *=.*/snapshot-interval = \"$snapshot_interval\"/" ~/.defund/config/app.toml
sed -i 's|^enable *=.*|enable = false|' $HOME/.defund/config/config.toml
sudo systemctl restart defundd && sudo journalctl -u defundd -f -o cat
echo " "
echo -e "\033[38;5;15;48;5;202mВведіть ім'я вашого гаманця\033[0m"
read YOUR_WALLET_NAME
echo "defundd keys add ${YOUR_WALLET_NAME}" >> $HOME/.bash_profile

defundd tx staking create-validator \
--amount=50ufetf \
--pubkey=$(defundd tendermint show-validator) \
--moniker="<Your moniker>" \
--identity=<Your identity> \
--details="<Your details>" \
--chain-id=orbit-alpha-1 \
--commission-rate=0.10 \
--commission-max-rate=0.20 \
--commission-max-change-rate=0.01 \
--min-self-delegation=1 \
--from=<YOUR_WALLET> \
--fees=20ufetf
-y
 
 sudo systemctl start defundd.service
echo " "
echo -e "\033[1;97;42mПеревірка статусу ноди\033[0m"
echo " " 
if [[ `service defund status | grep active` =~ "running" ]]; then
  echo -e "\033[1;97;42mDefund успішно встановлено\033[0m""
else
  echo -e "\033[30;97;41mDefund не встановлено, спробуйте ще раз та повідомте менторів\033[0m"
fi
echo "——————————————————————————————————————————————"

exit
