#!/bin/bash

echo "——————————————————————————————————————————————"
echo " "
echo -e "\033[1;97;42mОновлення пакетів...\033[0m"
sudo apt update && sudo apt upgrade -y
apt-get install libclang-dev
echo " "
echo -e "\033[1;97;42mВстановлення екрану...\033[0m"
sudo apt install screen
echo " "
echo -e "\033[1;97;42mВстановлення RUST...\033[0m"
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
source $HOME/.cargo/env
rustup toolchain install nightly
echo " "
echo -e "\033[1;97;42mВстановлення ноди...\033[0m"
cd $HOME
git clone --branch testnet https://github.com/massalabs/massa.git
enable_ipv6
echo " "

unset CHARCOUNT
echo -e "\e[43;30mВстановіть пароль до вашої ноди\033[0m"
CHARCOUNT=0
while IFS= read -p "$PROMPT" -r -s -n 1 CHAR
do
  if [[ $CHAR == $'\0' ]] ; then
    if [ $CHARCOUNT -gt 0 ] ; then
      break
    else
      echo
      echo -n "Не правильний пароль, довжина повинна бути більше 0 символів:"
      continue
    fi
  fi
  # Backspace
  if [[ $CHAR == $'\177' ]] ; then
    if [ $CHARCOUNT -gt 0 ] ; then
      CHARCOUNT=$((CHARCOUNT-1))
      PROMPT=$'\b \b'
      DASHPASS="${DASHPASS%?}"
    else
      PROMPT=''
    fi
  else
    CHARCOUNT=$((CHARCOUNT+1))
    PROMPT='*'
    PASS+="$CHAR"
  fi
done
echo " "
echo "Пароль збережено як:" $PASS
echo " "
cd massa/massa-node/
screen -S massa_node
RUST_BACKTRACE=full cargo run --release -- -p xxxxxxx|& tee logs.txt
