#!/bin/bash

echo " "
echo "——————————————————————————————————————————————"
echo " "

exists()
{
  command -v "$1" >/dev/null 2>&1
}
if exists curl; then
	echo ''
else
  sudo apt install curl -y < "/dev/null"
fi
bash_profile=$HOME/.bash_profile
if [ -f "$bash_profile" ]; then
    . $HOME/.bash_profile
fi

avail_space=`df $PWD -h | awk '/[0-9]%/{print $(NF-2)}' | sed 's/.$//'`
if [ $avail_space -lt 20 ]; then
	echo -e '\e[31mУ вас менше 20 ГБ вільного місця, звільніть місце та повторіть спробу встановлення.\e[39m'
	exit 1
fi

function setupVars {
	if [ ! $MESON_TOKEN ]; then
		read -p "Введіть свій токен meson: " MESON_TOKEN
		echo 'export MESON_TOKEN='${MESON_TOKEN} >> $HOME/.bash_profile
	fi
	echo -e '\n\e[42mВаш токен meson:' $MESON_TOKEN '\e[0m\n'
	if [ ! $MESON_PORT ]; then
		read -p "Введіть свій порт meson(за замовчуванням 19091): " MESON_PORT
		MESON_PORT=${MESON_PORT:-19091}
		echo 'export MESON_PORT='${MESON_PORT} >> $HOME/.bash_profile
	fi
	echo -e '\n\e[42mВаш порт mesin:' $MESON_PORT '\e[0m\n'
	if [ ! $MESON_SPACELIMIT ]; then
		echo -e '\e[42mНа даний момент у вас є' $avail_space 'GB вільного місця\e[0m'
		read -p "Введіть ліміт місця для Meson (at least 20GB), (ТІЛЬКИ ЧИСЛА без GB): " MESON_SPACELIMIT
		MESON_SPACELIMIT=${MESON_SPACELIMIT:-20}
		echo 'export MESON_SPACELIMIT='${MESON_SPACELIMIT} >> $HOME/.bash_profile
	fi
	echo -e '\n\e[42mYour Meson spacelimit:' $MESON_SPACELIMIT '\e[0m\n'
	. $HOME/.bash_profile
	sleep 1
}

function setupSwap {
	echo -e '\n\e[42mSet up swapfile\e[0m\n'
	curl -s https://api.nodes.guru/swap4.sh | bash
}
function installDeps {
	echo -e '\n\e[42mПідготовка до встановлення\e[0m\n' && sleep 1
	cd $HOME
	sudo apt update
	sudo apt install make clang pkg-config libssl-dev build-essential git jq ufw -y < "/dev/null"
}

function installSoftware {
	echo -e '\n\e[42mВстановлення програмного забезпечення\e[0m\n' && sleep 1
	ufw allow 80
	ufw allow 443
	ufw allow 19091
	wget -O meson.tar.gz https://staticassets.meson.network/public/meson_cdn/v3.1.19/meson_cdn-linux-amd64.tar.gz 
	tar -zxf meson.tar.gz
	cd ./meson_cdn-linux-amd64
#token = $MESON_TOKEN
#port = $MESON_PORT
	sudo ./meson_cdn config set --token=$MESON_TOKEN --https_port=$MESON_PORT --cache.size=30
	sudo $HOME/meson_cdn-linux-amd64/service install meson_cdn
	sudo systemctl daemon-reload
	sudo systemctl enable meson_cdn 
	sudo systemctl restart meson_cdn 
	echo -e '\n\e[42mCheck node status\e[0m\n' && sleep 3
	if [[ `sudo systemctl status meson_cdn | grep "active"` =~ "running" ]]; then
	  echo -e "Майнер meson \e[32mвстановлено\e[39m!"
	  echo -e "Ви можете перевірити його статус наступною командою \e[7msudo systemctl status meson_cdn\e[0m"
	  echo -e "Натисніть \e[7mQ\e[0m щоб вийти зі статусу меню"
	else
	  echo -e "Майнер meson \e[31mwas не встановлено\e[39m, спробуйте ще раз."
	fi
}


setupVars
setupSwap
installDeps
installSoftware
break

echo " "
echo "——————————————————————————————————————————————"
echo " "
