#!/bin/bash
echo "——————————————————————————————————————————————"
echo " "

source <(curl -s https://yar0slavvv.github.io/CPI-Nodes/nodes/ports.sh)
export -f selectPortSet && selectPortSet
echo ""
echo -e "\033[38;5;15;48;5;202mВпишіть назву ноди:\033[0m"
read NODE_MONIKER

CHAIN_ID="nibiru-itn-1"
CHAIN_DENOM="unibi"
BINARY_NAME="nibid"
BINARY_VERSION_TAG="v0.19.2"
CHEAT_SHEET="https://nodes.r1m-team.com/nibiru"

echo ""
echo -e "Moniker ноди:       \033[1;97;42m$NODE_MONIKER\033[0m"
echo -e "Chain id:           \033[1;97;42m$CHAIN_ID\033[0m"
echo -e "Chain demon:        \033[1;97;42m$CHAIN_DENOM\033[0m"
echo -e "Binary version tag: \033[1;97;42m$BINARY_VERSION_TAG\033[0m"
echo "——————————————————————————————————————————————"
echo ""
source <(curl -s https://yar0slavvv.github.io/CPI-Nodes/nodes//dependencies.sh)

cd $HOME || return
rm -rf nibiru
git clone https://github.com/NibiruChain/nibiru
cd $HOME/nibiru || return
git checkout v0.19.2
make install
nibid version # v0.19.2

nibid config keyring-backend os
nibid config chain-id $CHAIN_ID
nibid init "$NODE_MONIKER" --chain-id $CHAIN_ID

curl -s https://snapshots-testnet.stake-town.com/nibiru/genesis.json > $HOME/.nibid/config/genesis.json
curl -s https://snapshots-testnet.stake-town.com/nibiru/addrbook.json > $HOME/.nibid/config/addrbook.json

CONFIG_TOML=$HOME/.nibid/config/config.toml
PEERS=""
sed -i.bak -e "s/^persistent_peers *=.*/persistent_peers = \"$PEERS\"/" $CONFIG_TOML
SEEDS="a431d3d1b451629a21799963d9eb10d83e261d2c@seed-1.itn-1.nibiru.fi:26656,6a78a2a5f19c93661a493ecbe69afc72b5c54117@seed-2.itn-1.nibiru.fi:26656"
sed -i.bak -e "s/^seeds =.*/seeds = \"$SEEDS\"/" $CONFIG_TOML

APP_TOML=$HOME/.nibid/config/app.toml
sed -i 's|^pruning *=.*|pruning = "custom"|g' $APP_TOML
sed -i 's|^pruning-keep-recent  *=.*|pruning-keep-recent = "100"|g' $APP_TOML
sed -i 's|^pruning-keep-every *=.*|pruning-keep-every = "0"|g' $APP_TOML
sed -i 's|^pruning-interval *=.*|pruning-interval = "19"|g' $APP_TOML
sed -i -e "s/^filter_peers *=.*/filter_peers = \"true\"/" $CONFIG_TOML
indexer="null"
sed -i -e "s/^indexer *=.*/indexer = \"$indexer\"/" $CONFIG_TOML
sed -i 's|^minimum-gas-prices *=.*|minimum-gas-prices = "0.025unibi"|g' $APP_TOML

# Customize ports
CLIENT_TOML=$HOME/.nibid/config/client.toml
sed -i.bak -e "s/^external_address *=.*/external_address = \"$(wget -qO- eth0.me):$PORT_PPROF_LADDR\"/" $CONFIG_TOML
sed -i.bak -e "s%^proxy_app = \"tcp://127.0.0.1:26658\"%proxy_app = \"tcp://127.0.0.1:$PORT_PROXY_APP\"%; s%^laddr = \"tcp://127.0.0.1:26657\"%laddr = \"tcp://127.0.0.1:$PORT_RPC\"%; s%^pprof_laddr = \"localhost:6060\"%pprof_laddr = \"localhost:$PORT_P2P\"%; s%^laddr = \"tcp://0.0.0.0:26656\"%laddr = \"tcp://0.0.0.0:$PORT_PPROF_LADDR\"%; s%^prometheus_listen_addr = \":26660\"%prometheus_listen_addr = \":$PORT_PROMETHEUS\"%" $CONFIG_TOML && \
sed -i.bak -e "s%^address = \"0.0.0.0:9090\"%address = \"0.0.0.0:$PORT_GRPC\"%; s%^address = \"0.0.0.0:9091\"%address = \"0.0.0.0:$PORT_GRPC_WEB\"%; s%^address = \"tcp://0.0.0.0:1317\"%address = \"tcp://0.0.0.0:$PORT_API\"%" $APP_TOML && \
sed -i.bak -e "s%^node = \"tcp://localhost:26657\"%node = \"tcp://localhost:$PORT_RPC\"%" $CLIENT_TOML
echo ""
echo -e "\033[1;97;42mЗапуск та синхронізація ноди...\033[0m"
echo ""
sudo tee /etc/systemd/system/nibid.service > /dev/null << EOF
[Unit]
Description=Nibiru Node
After=network-online.target
[Service]
User=$USER
ExecStart=$(which nibid) start
Restart=on-failure
RestartSec=10
LimitNOFILE=10000
[Install]
WantedBy=multi-user.target
EOF

nibid tendermint unsafe-reset-all --home $HOME/.nibid --keep-addr-book

# Add snapshot here
URL="https://snapshots-testnet.stake-town.com/nibiru/nibiru-itn-1_latest.tar.lz4"
curl $URL | lz4 -dc - | tar -xf - -C $HOME/.nibid

sudo systemctl daemon-reload
sudo systemctl enable nibid
sudo systemctl start nibid

source $HOME/.bash_profile

echo -e "\033[38;5;15;48;5;202mВпишіть назву гаманця:\033[0m"
read wallet_name
nibid keys add $wallet_name
echo ""
echo -e "\033[38;5;15;48;5;202mОбов'язково збережіть всю інформацію про гаманець!\033[0m" && sleep 1
echo ""
echo -e "\033[1;97;42mНоду успішно встановлено\033[0m"
echo " "
echo -e "\033[1;97;42mДля того щоб вийти з меню натисніть Ctrl + C\033[0m"
echo "——————————————————————————————————————————————"
