#!/usr/bin/env bash

echo " "
echo "——————————————————————————————————————————————"
echo " "
set -e

sudo apt-get install curl

sudo apt update

bash <(curl -s https://yar0slavvv.github.io/CPI-Nodes/soft-installers/docker_install.sh)

curl -O https://gitlab.com/shardeum/validator/dashboard/-/raw/main/installer.sh && chmod +x installer.sh && ./installer.sh

