#!/bin/bash

echo " "
echo "——————————————————————————————————————————————"

exists()
{
  command -v "$1" >/dev/null 2>&1
}
if exists curl; then
	echo ''
else
  sudo apt update && sudo apt install curl -y < "/dev/null"
fi
bash_profile=$HOME/.bash_profile
if [ -f "$bash_profile" ]; then
    . $HOME/.bash_profile
fi

sudo apt update && sudo apt install ocl-icd-opencl-dev libopencl-clang-dev libgomp1 -y
cd $HOME
clear
wget -O subspace-cli https://github.com/subspace/subspace-cli/releases/download/v0.4.1-alpha/subspace-cli-ubuntu-x86_64-v3-v0.4.1-alpha
sudo chmod +x subspace-cli
sudo mv subspace-cli /usr/local/bin/
sudo rm -rf $HOME/.config/subspace-cli
/usr/local/bin/subspace-cli init
#systemctl stop subspaced subspaced-farmer &>/dev/null
#rm -rf ~/.local/share/subspace*

#source ~/.bash_profile
sleep 1

echo "[Unit]
Description=Subspace Node
After=network.target

[Service]
User=$USER
Type=simple
ExecStart=/usr/local/bin/subspace-cli farm --verbose
Restart=on-failure
LimitNOFILE=1024000

[Install]
WantedBy=multi-user.target" > $HOME/subspaced.service

mv $HOME/subspaced.service /etc/systemd/system/
sudo systemctl restart systemd-journald
sudo systemctl daemon-reload
sudo systemctl enable subspaced
sudo systemctl restart subspaced

echo "————————————————————————————————————————————————"
echo -e '\n\e[42mПеревірка статусу ноди\e[0m\n' && sleep 5
if [[ `service subspaced status | grep active` =~ "running" ]]; then
  echo -e "Ваша нода \e[32mвстановлена та успішно працює\e[39m!"
  echo -e "Ви миожете перевірити статус, цією командою \e[7mservice subspaced status\e[0m"
  echo -e "Натисніть \e[7mQ\e[0m щоб вийти з меню статусу"
else
  echo -e "Вашу ноду \e[31mне встановлно\e[39m, спробуйте ще раз."
fi

