#!/bin/bash

clear

bash <(curl -s https://yar0slavvv.github.io/CPI-Nodes/logos/upd/shardeum)


echo "     "
echo -e "\033[1;97;41mПеред тим як продовжити, запевніться що ваша нода\033[0m"
echo -e "\033[1;97;41mзупинена та зроблений Unstake!\033[0m"
echo "     "
echo -e "(\033[38;5;244m1\033[0m) Продовжити             (\033[38;5;244m2\033[0m) Повернутися"
echo "     "
while true; do
  read a
  
  case $a in
   1)
      bash <(curl -s https://yar0slavvv.github.io/CPI-Nodes/updates/launch/shardeum)
      ;;
   2)
      bash <(curl -s https://yar0slavvv.github.io/CPI-Nodes/updater)
      ;;
    *)
      echo "Невірний вибір"
      ;;
esac
done
