#!/bin/bash

clear

bash <(curl -s https://yar0slavvv.github.io/CPI-Nodes/logos/upd/shardeum)


echo "     "
echo -e "(\033[38;5;244m1\033[0m) Продовжити             (\033[38;5;244m2\033[0m) Повернутися"
echo "     "
while true; do
  read a
  
  case $a in
   1)
      curl -O https://gitlab.com/shardeum/validator/dashboard/-/raw/main/installer.sh && chmod +x installer.sh && ./installer.sh
      ;;
   2)
      bash <(curl -s https://yar0slavvv.github.io/CPI-Nodes/updater)
      ;;
    *)
      echo "Невірний вибір"
      ;;
esac
done
