#!/bin/bash

clear

bash <(curl -s https://yar0slavvv.github.io/CPI-Nodes/logos/uni/defund)

echo "     "
echo -e "(\033[38;5;244m1\033[0m) Продовжити                               (\033[38;5;244m2\033[0m) Повернутися"
echo "     "
while true; do
  read a
  case $a in
   1)
      echo "—————————————————————————————————————————————————————————————"
      sudo systemctl stop defund
      sudo systemctl disable defund
      cd $HOME
      rm /etc/systemd/system/defund.service
      rm /usr/local/bin/defundd
      rm -r defund/
      rm -r .defund/
      echo " "
      sleep 1
      echo -e "\033[1;97;42mDefund успішно видалено\033[0m"
      echo " "
      echo -e "\033[1;97;42mПовернення до головного меню...\033[0m"
      bash <(curl -s https://yar0slavvv.github.io/CPI-Nodes/main-menu)
      exit
      ;;
   2)
      bash <(curl -s https://yar0slavvv.github.io/CPI-Nodes/uninstaller)
      ;;
    *)
      echo "Невірний вибір"
      ;;
  esac
done
