#!/bin/bash

clear

bash <(curl -s https://yar0slavvv.github.io/CPI-Nodes/logos/uni/lamina1)

echo "     "
echo -e "(\033[38;5;244m1\033[0m) Продовжити                               (\033[38;5;244m2\033[0m) Повернутися"
echo "     "
while true; do
  read a
  case $a in
   1)
      echo "—————————————————————————————————————————————————————————————"
      systemctl stop lamina1
      systemctl disable lamina1
      rm -rf ~/lamina1 ~/.lamina1 /etc/systemd/system/lamina1.service
      echo " "
      sleep 1
      echo -e "\033[1;97;42mLamina1 успішно видалено\033[0m"
      echo " "
      echo -e "\033[1;97;42mПовернення до головного меню...\033[0m"
      sleep 3
      bash <(curl -s https://yar0slavvv.github.io/CPI-Nodes/main-menu)
      ;;
   2)
      bash <(curl -s https://yar0slavvv.github.io/CPI-Nodes/uninstaller)
      ;;
    *)
      echo "Невірний вибір"
      ;;
  esac
done
