#!/bin/bash

clear

bash <(curl -s https://yar0slavvv.github.io/CPI-Nodes/logos/uni/meson)

echo "     "
echo -e "(\033[38;5;244m1\033[0m) Продовжити                               (\033[38;5;244m2\033[0m) Повернутися"
echo "     "
while true; do
  read a
  
  case $a in
   1)
      sudo systemctl disable meson_cdn
      sudo systemctl stop meson_cdn
      echo ""
      echo -e '\n\e[42meson успішно видалено\e[0m\n'
      ;;
   2)
      bash <(curl -s https://yar0slavvv.github.io/CPI-Nodes/uninstaller)
      ;;
    *)
      echo "Невірний вибір"
      ;;
esac
done
