#!/bin/bash

clear

bash <(curl -s https://yar0slavvv.github.io/CPI-Nodes/logos/uni/nibiru)

echo "     "
echo -e "(\033[38;5;244m1\033[0m) Продовжити                               (\033[38;5;244m2\033[0m) Повернутися"
echo "     "
while true; do
  read a
  
  case $a in
   1)
      systemctl stop nibid
      systemctl disable nibid
      rm -rf $(which nibid) ~/.nibid ~/nibiru
      echo -e "\033[1;97;42mNibiru успішно видалено\033[0m"
      echo " "
      ;;
   2)
      bash <(curl -s https://yar0slavvv.github.io/CPI-Nodes/uninstaller)
      ;;
    *)
      echo "Невірний вибір"
      ;;
esac
done
