#!/bin/bash

clear

bash <(curl -s https://yar0slavvv.github.io/CPI-Nodes/logos/uni/subspace)

echo "     "
echo -e "(\033[38;5;244m1\033[0m) Продовжити                               (\033[38;5;244m2\033[0m) Повернутися"
echo "     "
while true; do
  read a
  
  case $a in
   1)
      sudo systemctl stop subspaced subspaced-farmer
      sudo systemctl disable subspaced subspaced-farmer
      rm -rf ~/.local/share/subspace*
      rm -rf /etc/systemd/system/subspace*
      rm -rf /usr/local/bin/subspace*
      echo ""
      echo -e "\033[1;97;42mSubspace успішно видалено\033[0m"
      exit
      ;;
   2)
      bash <(curl -s https://yar0slavvv.github.io/CPI-Nodes/uninstaller)
      ;;
    *)
      echo "Невірний вибір"
      ;;
esac
done
